- type: job
  id: Passenger
  name: job-name-passenger
  description: job-description-passenger
  subnames:
  - Male: ассистент
    Female: ассистентка
  - Male: художник
    Female: художница
  - Male: юрист
  - Male: фрилансер
  - Male: экипаж вне службы
  - Male: турист
  - Male: психолог
  playTimeTracker: JobPassenger
  startingGear: PassengerGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-everyone
#  access: # WL-Changes
#  - Maintenance
  bonusSkillPoints: 16 # WL-Skills / Why? / bcs если какой-то там пассажир смог попасть на станцию, то наверное в каких-то навыках он и выдается и так как подвязать конкретные навыки ему низя, то остается дать ему бОльшую вариативность в собственном выборе навыков :3

- type: startingGear
  id: PassengerGear
  equipment:
    id: PassengerPDA
    ears: ClothingHeadsetGrey
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: PassengerChameleonOutfit
  job: Passenger
  equipment:
    head: ClothingHeadHatWelding
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckMantle
    outerClothing: ClothingOuterWinterCoat
    gloves: ClothingHandsGlovesColorYellowBudget
